name: Java CI

on: [push, pull_request]  # Chạy khi có push hoặc pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Lấy code từ GitHub

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test
      run: mvn test  # Chạy kiểm thử JUnit
